# Global configuration settings.

# Player kit setup.  In order for a player to get a kit when they spawn they
# must have a permission similar to 'ac.kits.normal'.  If a player has more
# than one kit permission, they will get all kits they have the proper
# permssion nodes for.
kits:
  ac:
    normal:
      - id: 288
        name: Feather of Flight
      - id: 268
        name: Wooden Knife
    donor:
      - id: 267
        name: Combat Knife
      - id: 307
        name: Body Armor
        wear: chest
      - id: 292
        name: AK-47
      - id: 337
        name: Ammo
        quantity: 64